language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"

before_install:
  - cpanm --notest Minilla Carton

install:
  - carton install

script:
  - carton exec -- minil test --all
